version: '2'
services:
    gestaoagricola-app:
        image: gestaoagricola
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestaoagricola-mysql:3306/gestaoagricola?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestaoagricola-mysql:
        extends:
            file: mysql.yml
            service: gestaoagricola-mysql
